travel_guard_required_files = {
    "trip_cancellation": {
        "illness": [
            "booking_confirmation",
            "supporting_claim_evidence_documentation",
            "proof_of_cancellation",
            "proof_of_payment_for_claimed_expenses",
            "documentation_of_diagnosis_and_treatment_dates",
        ],
        "injury": [
            "booking_confirmation",
            "supporting_claim_evidence_documentation",
            "proof_of_cancellation",
            "proof_of_payment_for_claimed_expenses",
            "documentation_of_diagnosis_and_treatment_dates",
        ],
        "pregnancy": [
            "booking_confirmation",
            "supporting_claim_evidence_documentation",
            "proof_of_cancellation",
            "proof_of_payment_for_claimed_expenses",
            "documentation_of_diagnosis_and_treatment_dates",
        ],
        "death": [
            "booking_confirmation",
            "supporting_claim_evidence_documentation",
            "proof_of_cancellation",
            "proof_of_payment_for_claimed_expenses",
            "death_certificate",
        ],
        "work": [
            "booking_confirmation",
            "supporting_claim_evidence_documentation",
            "proof_of_cancellation",
            "proof_of_payment_for_claimed_expenses",
            "evidence_of_work_employment_reasons",
        ],
        "military": [
            "booking_confirmation",
            "supporting_claim_evidence_documentation",
            "proof_of_cancellation",
            "proof_of_payment_for_claimed_expenses",
            "official_military_order_or_letter",
        ],
        "uninhabitable": [
            "booking_confirmation",
            "supporting_claim_evidence_documentation",
            "proof_of_cancellation",
            "proof_of_payment_for_claimed_expenses",
            "police_report",
            "evidence_of_damage_to_home_or_destination",
            "proof_of_residential_address",
        ],
        "court": [
            "booking_confirmation",
            "supporting_claim_evidence_documentation",
            "proof_of_cancellation",
            "proof_of_payment_for_claimed_expenses",
            "court_order_jury_summons_or_subpoena",
        ],
        "weather": [
            "booking_confirmation",
            "supporting_claim_evidence_documentation",
            "proof_of_cancellation",
            "proof_of_payment_for_claimed_expenses",
            "travel_carrier_statement",
        ],
        "carrier": [
            "booking_confirmation",
            "supporting_claim_evidence_documentation",
            "proof_of_cancellation",
            "proof_of_payment_for_claimed_expenses",
        ],
        "other": [
            "booking_confirmation",
            "supporting_claim_evidence_documentation",
            "proof_of_cancellation",
            "proof_of_payment_for_claimed_expenses",
        ],
    },
    "trip_interruption": {
        "illness": [
            "booking_confirmation",
            "supporting_claim_evidence_documentation",
            "confirmation_of_interruption",
            "proof_of_payment_for_claimed_expenses",
            "documentation_of_diagnosis_and_treatment_dates",
        ],
        "injury": [
            "booking_confirmation",
            "supporting_claim_evidence_documentation",
            "confirmation_of_interruption",
            "proof_of_payment_for_claimed_expenses",
            "documentation_of_diagnosis_and_treatment_dates",
        ],
        "pregnancy": [
            "booking_confirmation",
            "supporting_claim_evidence_documentation",
            "confirmation_of_interruption",
            "proof_of_payment_for_claimed_expenses",
            "documentation_of_diagnosis_and_treatment_dates",
        ],
        "death": [
            "booking_confirmation",
            "supporting_claim_evidence_documentation",
            "confirmation_of_interruption",
            "proof_of_payment_for_claimed_expenses",
            "death_certificate",
        ],
        "work": [
            "booking_confirmation",
            "supporting_claim_evidence_documentation",
            "confirmation_of_interruption",
            "proof_of_payment_for_claimed_expenses",
            "evidence_of_work_employment_reasons",
        ],
        "military": [
            "booking_confirmation",
            "supporting_claim_evidence_documentation",
            "confirmation_of_interruption",
            "proof_of_payment_for_claimed_expenses",
            "official_military_order_or_letter",
        ],
        "uninhabitable": [
            "booking_confirmation",
            "supporting_claim_evidence_documentation",
            "confirmation_of_interruption",
            "proof_of_payment_for_claimed_expenses",
            "police_report",
            "evidence_of_damage_to_home_or_destination",
            "proof_of_residential_address",
        ],
        "court": [
            "booking_confirmation",
            "supporting_claim_evidence_documentation",
            "confirmation_of_interruption",
            "proof_of_payment_for_claimed_expenses",
            "court_order_jury_summons_or_subpoena",
        ],
        "weather": [
            "booking_confirmation",
            "supporting_claim_evidence_documentation",
            "confirmation_of_interruption",
            "proof_of_payment_for_claimed_expenses",
            "travel_carrier_statement",
        ],
        "carrier": [
            "booking_confirmation",
            "supporting_claim_evidence_documentation",
            "confirmation_of_interruption",
            "proof_of_payment_for_claimed_expenses",
        ],
        "other": [
            "booking_confirmation",
            "supporting_claim_evidence_documentation",
            "confirmation_of_interruption",
            "proof_of_payment_for_claimed_expenses",
        ],
    },
    "trip_delay": {
        "illness": [
            "booking_confirmation",
            "supporting_claim_evidence_documentation",
            "confirmation_of_interruption",
            "proof_of_payment_for_claimed_expenses",
            "documentation_of_diagnosis_and_treatment_dates",
        ],
        "injury": [
            "booking_confirmation",
            "supporting_claim_evidence_documentation",
            "confirmation_of_interruption",
            "proof_of_payment_for_claimed_expenses",
            "documentation_of_diagnosis_and_treatment_dates",
        ],
        "pregnancy": [
            "booking_confirmation",
            "supporting_claim_evidence_documentation",
            "confirmation_of_interruption",
            "proof_of_payment_for_claimed_expenses",
            "documentation_of_diagnosis_and_treatment_dates",
        ],
        "death": [
            "booking_confirmation",
            "supporting_claim_evidence_documentation",
            "confirmation_of_interruption",
            "proof_of_payment_for_claimed_expenses",
            "death_certificate",
        ],
        "work": [
            "booking_confirmation",
            "supporting_claim_evidence_documentation",
            "confirmation_of_interruption",
            "proof_of_payment_for_claimed_expenses",
            "evidence_of_work_employment_reasons",
        ],
        "military": [
            "booking_confirmation",
            "supporting_claim_evidence_documentation",
            "confirmation_of_interruption",
            "proof_of_payment_for_claimed_expenses",
            "official_military_order_or_letter",
        ],
        "uninhabitable": [
            "booking_confirmation",
            "supporting_claim_evidence_documentation",
            "confirmation_of_interruption",
            "proof_of_payment_for_claimed_expenses",
            "police_report",
            "evidence_of_damage_to_home_or_destination",
            "proof_of_residential_address",
        ],
        "court": [
            "booking_confirmation",
            "supporting_claim_evidence_documentation",
            "confirmation_of_interruption",
            "proof_of_payment_for_claimed_expenses",
            "court_order_jury_summons_or_subpoena",
        ],
        "weather": [
            "booking_confirmation",
            "supporting_claim_evidence_documentation",
            "confirmation_of_interruption",
            "proof_of_payment_for_claimed_expenses",
            "travel_carrier_statement",
        ],
        "carrier": [
            "booking_confirmation",
            "supporting_claim_evidence_documentation",
            "confirmation_of_interruption",
            "proof_of_payment_for_claimed_expenses",
        ],
        "other": [
            "booking_confirmation",
            "supporting_claim_evidence_documentation",
            "confirmation_of_interruption",
            "proof_of_payment_for_claimed_expenses",
        ],
    },
    # OUT OF SCOPE
    # "baggage": {
    #     "loss": [
    #         "booking_confirmation",
    #         "supporting_claim_evidence_documentation",
    #         "report_from_liable_party_or_police",
    #         "evidence_of_damages",
    #         "repair_quotation_for_damaged_items",
    #         "purchase_receipt_of_damaged_item",
    #         "proof_of_value_and_ownership_of_damaged_property",
    #     ],
    #     "delay": [
    #         "booking_confirmation",
    #         "supporting_claim_evidence_documentation",
    #         "report_from_liable_party_or_police",
    #         "evidence_of_damages",
    #         "repair_quotation_for_damaged_items",
    #         "purchase_receipt_of_damaged_item",
    #         "proof_of_value_and_ownership_of_damaged_property",
    #         "receipts_for_essential_purchases",
    #         "property_irregularity_report",
    #         "confirmation_of_returned_luggage",
    #         "carrier_reimbursement_documentation",
    #     ],
    # },
    # "medical": {
    #     "medical": [
    #         "booking_confirmation",
    #         "supporting_claim_evidence_documentation",
    #         "documentation_of_diagnosis_and_treatment_dates",
    #         "medical_expense_receipts",
    #         "death_certificate_if_applicable",
    #     ]
    # },
    # "cdw": {
    #     "cdw": [
    #         "booking_confirmation",
    #         "supporting_claim_evidence_documentation",
    #         "proof_of_comprehensive_motor_insurance",
    #         "policy_wording_of_comprehensive_motor_insurance",
    #         "proof_of_payment_to_rental_agency_for_damages",
    #         "photos_of_damaged_vehicle",
    #         "police_report_and_rental_agency_incident_report",
    #         "driving_license",
    #     ]
    # },
}


cover_more_document_check = {
    "General": [
        "Travel itinerary or summary of travel plans",
        "Letter of explanation (if required documents are missing)",
    ],
    "Overseas Medical and Dental": [
        "Medical reports from treating overseas provider",
        "All invoices and receipts",
        "Written confirmation from treating dentist (for dental claims)",
        "Medical Authority (page 9)",
        "Medical Certificate (page 9)",
    ],
    "Additional Expenses": [
        "All invoices and receipts",
        "Medical report from treating overseas practitioner (if due to health)",
        "Medical Certificate (page 9)",
        "Medical Authority (page 9)",
    ],
    "Amendment or Cancellation Costs": [
        "Medical Certificate (page 9) (if due to health)",
        "Medical Authority (page 9) (if due to health)",
        "Airline's fare sheet/rules (for international flights)",
        "Confirmation of credit cancellation (for domestic flights)",
    ],
}
