# type: ignore
"""added more data fields in Request tbl

Revision ID: 05ae6ac50f00
Revises: 5b26fa47d930
Create Date: 2025-11-04 09:26:10.890091+00:00

"""
from __future__ import annotations

import warnings
from typing import TYPE_CHECKING

import sqlalchemy as sa
from alembic import op
from advanced_alchemy.types import EncryptedString, EncryptedText, GUID, ORA_JSONB, DateTimeUTC
from sqlalchemy import Text  # noqa: F401

if TYPE_CHECKING:
    from collections.abc import Sequence

__all__ = ["downgrade", "upgrade", "schema_upgrades", "schema_downgrades", "data_upgrades", "data_downgrades"]

sa.GUID = GUID
sa.DateTimeUTC = DateTimeUTC
sa.ORA_JSONB = ORA_JSONB
sa.EncryptedString = EncryptedString
sa.EncryptedText = EncryptedText

# revision identifiers, used by Alembic.
revision = '05ae6ac50f00'
down_revision = '5b26fa47d930'
branch_labels = None
depends_on = None


def upgrade() -> None:
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", category=UserWarning)
        with op.get_context().autocommit_block():
            schema_upgrades()
            data_upgrades()

def downgrade() -> None:
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", category=UserWarning)
        with op.get_context().autocommit_block():
            data_downgrades()
            schema_downgrades()

def schema_upgrades() -> None:
    """schema upgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('summary_of_findings', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('case_description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('decision_confidence_level', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('is_fraud_suspected', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('fraud_reasons', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('matched_coverage_terms', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('client_business_number', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('policy_total_cost', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###

def schema_downgrades() -> None:
    """schema downgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('requests', schema=None) as batch_op:
        batch_op.drop_column('policy_total_cost')
        batch_op.drop_column('client_business_number')
        batch_op.drop_column('matched_coverage_terms')
        batch_op.drop_column('fraud_reasons')
        batch_op.drop_column('is_fraud_suspected')
        batch_op.drop_column('decision_confidence_level')
        batch_op.drop_column('case_description')
        batch_op.drop_column('summary_of_findings')

    # ### end Alembic commands ###

def data_upgrades() -> None:
    """Add any optional data upgrade migrations here!"""

def data_downgrades() -> None:
    """Add any optional data downgrade migrations here!"""
