# type: ignore
"""db init setup

Revision ID: d95f49b93cd0
Revises: 
Create Date: 2025-10-27 07:53:10.755860+00:00

"""
from __future__ import annotations

import warnings
from typing import TYPE_CHECKING

import sqlalchemy as sa
from alembic import op
from advanced_alchemy.types import EncryptedString, EncryptedText, GUID, ORA_JSONB, DateTimeUTC
from sqlalchemy import Text  # noqa: F401
from sqlalchemy.dialects import postgresql
if TYPE_CHECKING:
    from collections.abc import Sequence

__all__ = ["downgrade", "upgrade", "schema_upgrades", "schema_downgrades", "data_upgrades", "data_downgrades"]

sa.GUID = GUID
sa.DateTimeUTC = DateTimeUTC
sa.ORA_JSONB = ORA_JSONB
sa.EncryptedString = EncryptedString
sa.EncryptedText = EncryptedText

# revision identifiers, used by Alembic.
revision = 'd95f49b93cd0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", category=UserWarning)
        with op.get_context().autocommit_block():
            schema_upgrades()
            data_upgrades()

def downgrade() -> None:
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", category=UserWarning)
        with op.get_context().autocommit_block():
            data_downgrades()
            schema_downgrades()

def schema_upgrades() -> None:
    """schema upgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer',
    sa.Column('id', sa.GUID(length=16), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('email_address', sa.String(length=255), nullable=True),
    sa.Column('hashed_name', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=True),
    sa.Column('sa_orm_sentinel', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_customer'))
    )
    op.create_table('role',
    sa.Column('id', sa.GUID(length=16), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('sa_orm_sentinel', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_role')),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('name', name=op.f('uq_role_name')),
    sa.UniqueConstraint('slug', name='uq_role_slug')
    )
    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.create_index('ix_role_slug_unique', ['slug'], unique=True)

    op.create_table('user_account',
    sa.Column('id', sa.GUID(length=16), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('verified_at', sa.Date(), nullable=True),
    sa.Column('joined_at', sa.Date(), nullable=False),
    sa.Column('login_count', sa.Integer(), nullable=False),
    sa.Column('sa_orm_sentinel', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_account'))
    )
    with op.batch_alter_table('user_account', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_account_email'), ['email'], unique=True)

    op.create_table('requests',
    sa.Column('id', sa.GUID(length=16), nullable=False),
    sa.Column('request_number', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('submission_status', sa.Enum('PROCESSING', 'INREVIEW', 'CLOSED', 'ERROR', 'DUPLICATE', name='submissionstatus'), nullable=False),
    sa.Column('missing_documents', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('generated_decision_summary', sa.Text(), nullable=True),
    sa.Column('hashed_code', sa.String(length=2550), nullable=True),
    sa.Column('decision_reason', sa.Text(), nullable=True),
    sa.Column('payment_status', sa.Text(), nullable=True),
    sa.Column('payment_reason', sa.Text(), nullable=True),
    sa.Column('claim_number', sa.Text(), nullable=True),
    sa.Column('approved_amount', sa.Text(), nullable=True),
    sa.Column('type_of_claim', sa.Text(), nullable=True),
    sa.Column('requested_reimbursement_amount', sa.Text(), nullable=True),
    sa.Column('insurance_agency_name', sa.Text(), nullable=True),
    sa.Column('premium_amount', sa.Text(), nullable=True),
    sa.Column('trip_cost', sa.Text(), nullable=True),
    sa.Column('trip_start_date', sa.DateTime(), nullable=True),
    sa.Column('trip_return_date', sa.DateTime(), nullable=True),
    sa.Column('destination', sa.String(length=2550), nullable=True),
    sa.Column('client_name', sa.String(length=2550), nullable=True),
    sa.Column('client_email_address', sa.Text(), nullable=True),
    sa.Column('client_phone_number', sa.Text(), nullable=True),
    sa.Column('client_post_code', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('policy_holder', sa.Text(), nullable=True),
    sa.Column('policy_number', sa.Text(), nullable=True),
    sa.Column('policy_effective_date', sa.DateTime(), nullable=True),
    sa.Column('policy_expiration_date', sa.DateTime(), nullable=True),
    sa.Column('maximum_coverage_amount', sa.Text(), nullable=True),
    sa.Column('coverage_limits', sa.Text(), nullable=True),
    sa.Column('generated_decisions', sa.Text(), nullable=True),
    sa.Column('generated_thoughts', sa.Text(), nullable=True),
    sa.Column('unique_identifier', sa.Text(), nullable=True),
    sa.Column('customer_id', sa.GUID(length=16), nullable=True),
    sa.Column('created_by_id', sa.GUID(length=16), nullable=True),
    sa.Column('sa_orm_sentinel', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['user_account.id'], name=op.f('fk_requests_created_by_id_user_account')),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], name=op.f('fk_requests_customer_id_customer')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_requests')),
    sa.UniqueConstraint('request_number'),
    sa.UniqueConstraint('request_number', name=op.f('uq_requests_request_number'))
    )
    op.create_table('user_account_role',
    sa.Column('id', sa.GUID(length=16), nullable=False),
    sa.Column('user_id', sa.GUID(length=16), nullable=False),
    sa.Column('role_id', sa.GUID(length=16), nullable=False),
    sa.Column('assigned_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('sa_orm_sentinel', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], name=op.f('fk_user_account_role_role_id_role'), ondelete='cascade'),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.id'], name=op.f('fk_user_account_role_user_id_user_account'), ondelete='cascade'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_account_role'))
    )
    op.create_table('chats',
    sa.Column('id', sa.GUID(length=16), nullable=False),
    sa.Column('user_id', sa.GUID(length=16), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('request_id', sa.GUID(length=16), nullable=True),
    sa.Column('customer_id', sa.GUID(length=16), nullable=True),
    sa.Column('sa_orm_sentinel', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['user_account.id'], name=op.f('fk_chats_customer_id_user_account'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['request_id'], ['requests.id'], name=op.f('fk_chats_request_id_requests'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.id'], name=op.f('fk_chats_user_id_user_account'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chats')),
    sa.UniqueConstraint('request_id'),
    sa.UniqueConstraint('request_id', name=op.f('uq_chats_request_id'))
    )
    op.create_table('extractions',
    sa.Column('id', sa.GUID(length=16), nullable=False),
    sa.Column('request_id', sa.GUID(length=16), nullable=False),
    sa.Column('extracted_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('sa_orm_sentinel', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['requests.id'], name=op.f('fk_extractions_request_id_requests')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_extractions'))
    )
    op.create_table('chat_messages',
    sa.Column('id', sa.GUID(length=16), nullable=False),
    sa.Column('chat_id', sa.GUID(length=16), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('sa_orm_sentinel', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], name=op.f('fk_chat_messages_chat_id_chats'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chat_messages'))
    )
    op.create_table('request_attachments',
    sa.Column('id', sa.GUID(length=16), nullable=False),
    sa.Column('chat_id', sa.GUID(length=16), nullable=True),
    sa.Column('file_name', sa.String(), nullable=False),
    sa.Column('url', sa.String(length=250), nullable=False),
    sa.Column('sa_orm_sentinel', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], name=op.f('fk_request_attachments_chat_id_chats')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_request_attachments'))
    )
    # ### end Alembic commands ###

def schema_downgrades() -> None:
    """schema downgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('request_attachments')
    op.drop_table('chat_messages')
    op.drop_table('extractions')
    op.drop_table('chats')
    op.drop_table('user_account_role')
    op.drop_table('requests')
    with op.batch_alter_table('user_account', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_account_email'))

    op.drop_table('user_account')
    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.drop_index('ix_role_slug_unique')

    op.drop_table('role')
    op.drop_table('customer')
    # ### end Alembic commands ###

def data_upgrades() -> None:
    """Add any optional data upgrade migrations here!"""

def data_downgrades() -> None:
    """Add any optional data downgrade migrations here!"""